bkvivu/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from profilepage import views as profileViews
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('homepage/')),
    path('admin/', admin.site.urls),
    path('logout/', profileViews.logout_view, name = 'logout'),
    path('homepage/', include('homepage.urls')),
    path('postspage/', include('postspage.urls')),
    path('profile/', include('profilepage.urls')),
    path('settings/', include('settingspage.urls')),
    path('shoppingcart/', include('shoppingcart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

settingspage/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'settingspage'
urlpatterns = [
    path('', views.settingsPage, name='settingsPage'),
    path('general/', views.generalPage, name='gerenalPage'),

    path('posts', views.testPostPage, name='testPostPage'),
    path('posts/addPosts', views.testCreatePosts, name='testCreatePosts'),
    path('posts/delete/<int:postId>/', views.testDeletePost, name='testDeletePost'),
    path('posts/edit/<int:postId>/', views.testEditPost, name="testEditPost"),
    path('posts/edit/<int:postId>/testDeleteImagePost/<int:imageId>', views.testDeleteImagePost, name='testDeleteImagePost'),
    path('posts/edit/<int:postId>/testRecoverDelete/', views.testRecoverDelete, name="testRecoverDelete"),

    path('product/', views.ProductManager, name='product'),
    path('product/add', views.CreateProduct.as_view(), name='addProduct'),
    path('product/delete/<int:product_id>', views.deleteProduct, name='deleteProduct'),
    path('product/edit/<int:product_id>', views.editProduct.as_view(), name='editProduct'),


    path('bills/', views.billsPage, name='billsPage'),
    path('bills/viewBill/<int:billId>', views.viewBill, name='viewBill'),
    path('bills/viewBill/<int:billId>/accept/>', views.accept, name='accept'),
    path('bills/viewBill/<int:billId>/decline/>', views.decline, name='decline'),


    path('statistics/', views.statisticsPage, name='statisticsPage'),

    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_URL)

settingspage/forms.py
from django import forms
from homepage.models import *

class UpdateSharerForm(forms.ModelForm):
    class Meta:
        model = Sharer
        fields = ("name", "avatar")

class UpdateManagerForm(forms.ModelForm):
    class Meta:
        model = Manager
        fields = ("name","avatar", "address", "bio")

class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'address', 'provider')

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('type', 'name','describe' , 'price', 'img',)

class CreateImgForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ('img',)
        # widgets = {
        #     'img' : forms.FileInput(attrs={'class' : '11'})
        # }
        
class CreatePostFormTest(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'address', 
                  'city', 'district', 'ward',
                  'provider')

settingspage/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.views import View
from django.forms import formset_factory
from django.forms import modelformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from homepage.models import *
from .forms import *
from django.http import JsonResponse
import json
from .urls import *
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect
from datetime import datetime
from func.func import *

from collections import OrderedDict
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json


ImageUploadFormSet = modelformset_factory(Image, CreateImgForm, extra=0, can_delete=True)


# Create your views here.
def settingsPage(request):
    return redirect('settingspage:gerenalPage')



#####-------- Sản phẩm -------######
# ProductPage
def ProductManager(request):
    acc = Account.objects.get(user_ptr=request.user)
    user = Sharer.objects.get(account= acc) if acc.role == 'sharer' else Manager.objects.get(account= acc)
    context = {
        'acc' : acc,
        'user' : user
    }
    return render(request, 'products/product.html', context)
#Tạo sản phẩm mới
class CreateProduct(View):
    def get(self, request):
        form_product = ProductForm()
        acc = Account.objects.get(user_ptr=request.user)
        context = {
            'acc' : acc,
            'form_product':form_product
        }
        return render(request, 'products/addproduct.html', context)
    def post(self, request):
        acc = Account.objects.get(user_ptr=request.user)
        if acc.role == 'sharer':
            return HttpResponse("Bạn cần là người quản lý để thực hiện")
        else:
            user = Manager.objects.get(account = acc)
            newProduct = Product.objects.create(provider = user)
            form_product = ProductForm(request.POST, request.FILES, instance= newProduct)
            if form_product.is_valid():
                if form_product.cleaned_data['img'].name == 'default.jpg':
                    messages.error(request, "Thêm sản phẩm thất bại vì thiếu hình ảnh")
                    newProduct.delete()
                    return redirect('settingspage:product')
                product = form_product.save(commit= False) # Đối tượng mô hình k đưa vào cơ sở dữ liệu
                product.save()
                messages.success(request, "Thêm sản phẩm thành công")
            else:
                newProduct.delete()
                messages.error(request, "Thêm sản phẩm thất bại")
            return redirect('settingspage:product')


#Xóa Sản phẩm
def deleteProduct(request, product_id):
    try:
        product = Product.objects.get(pk = product_id)
        product.delete()
        messages.success(request, "Đã xóa sản phẩm")
    except:
        messages.error(request, "Thao tác lỗi")
    return redirect('settingspage:product')

# Sửa sản phẩm
class editProduct(View):
    def get(self, request, product_id):
        acc = Account.objects.get(user_ptr=request.user)
        user = Sharer.objects.get(account= acc) if acc.role == 'sharer' else Manager.objects.get(account= acc)
        _product = Product.objects.get(pk = product_id)
        pform = ProductForm(instance= _product)
        context = {
            'form_product': pform,
            'acc': acc,
        }
        return render(request, 'products/addproduct.html', context)
    def post(self, request, product_id):
        _product = Product.objects.get(pk = product_id)
        pform = ProductForm(request.POST, request.FILES, instance = _product)
        if pform.is_valid():
            pform.save()
            messages.success(request, "Đã lưu thay đổi")
        else :
            messages.error(request, "Thực hiện bị lỗi")
        return redirect('settingspage:product')

#generalPage
def generalPage(request):
    acc = Account.objects.get(user_ptr=request.user)
    user = Sharer.objects.get(account= acc) if acc.role == 'sharer' else Manager.objects.get(account= acc)

    if request.method == 'POST':
        if acc.role == 'sharer':
            user.name = request.POST.get('name')
            user.age = request.POST.get('age')
            user.bio = request.POST.get('comment')

            city_id = request.POST.get('city')
            district_id = request.POST.get('district')
            ward_id = request.POST.get('ward')

            user.city, user.district, user.ward = getArea(city_id, district_id, ward_id)

            if 'avatar' in request.FILES:
                user.avatar = request.FILES.get('avatar')
            user.save()
            context = {
                'role': acc.role,
                'acc': acc,
                'user': user,
            }

            return render(request, 'general/general.html', context)
        else:
            user.name = request.POST.get('name')
            user.phone = request.POST.get('phone')
            user.address = request.POST.get('address')
            user.bio = request.POST.get('comment')
            user.t_open = request.POST.get('t_open')
            user.t_closed = request.POST.get('t_closed')

            city_id = request.POST.get('city')
            district_id = request.POST.get('district')
            ward_id = request.POST.get('ward')

            user.city, user.district, user.ward = getArea(city_id, district_id, ward_id)
            if 'avatar' in request.FILES:
                user.avatar = request.FILES.get('avatar')
            if 'bank' in request.FILES:
                user.bank = request.FILES.get('bank')
            user.facebook_link = request.POST.get('facebook_link')
            user.website_link = request.POST.get('website_link')
            user.save()
            context = {
                'role': acc.role,
                'acc': acc,
                'user': user,
                'time_open': user.t_open,
                'time_close': user.t_closed,
            }

            return render(request, 'general/general.html', context)
    if acc.role == 'manager':   
        time_open = user.t_open.strftime("%H:%M")
        time_close = user.t_closed.strftime("%H:%M")

        context = {
            'role': acc.role,
            'acc': acc,
            'user': user,
            'time_open': time_open,
            'time_close': time_close,
        }
    else:
        context = {
            'role': acc.role,
            'acc': acc,
            'user': user,
        }
    return render(request, 'general/general.html', context)

#Bill Page
def billsPage(request):
   
    acc = Account.objects.get(user_ptr=request.user)
    user = Sharer.objects.get(account= acc) if acc.role == 'sharer' else Manager.objects.get(account= acc)
    bills = user.bill_set.all()
    # Cập nhật trạng thái thanh toán nếu quá hạn
    for bill in bills:
        if not bill.img and (timezone.now() - bill.time).total_seconds() > 600:
            bill.status = "Timeout"
            bill.save()
    selected_data = request.GET.get('selectedData', 'Waiting')
    context = {
        "bills" : bills,
        "acc" : acc,
        "user" : user,
        "data_from_js" : selected_data,
    }
    return render(request, "bills/bills.html", context)

def viewBill(request, billId):
    if request.method == 'GET' :
        bill = Bill.objects.get(id = billId)
        user = Sharer.objects.get(account_id=bill.acc_id) if bill.acc.role=='sharer' else Manager.objects.get(account_id=bill.acc_id) 
        return render(request, "bills/bill.html", {"bill" : bill, 'user': user})
    
def accept(request, billId):
    try :
        bill = Bill.objects.get(pk = billId)
        bill.status = "Accept"
        bill.save()
        # bill.delete()
        messages.success(message='Accept', request=request)
        return redirect('settingspage:billsPage')
    except :
        messages.success(message='Error happened, try again', request=request)
        return redirect('settingspage:billsPage')
def decline(request,billId):
    try :
        bill = Bill.objects.get(pk = billId)
        bill.status = "Decline"
        bill.save()
        # bill.delete()
        messages.success(message='Decline', request=request)
        return redirect('settingspage:billsPage')
    except :
        messages.success(message='Error happened, try again', request=request)
        return redirect('settingspage:billsPage')


    

# postPage
def testPostPage(request):
    acc = Account.objects.get(user_ptr=request.user)
    postList = acc.post_set.all()
    context = {
        'acc': acc,
        'postList': postList,
    }
    return render(request, 'posts/postList.html', context)

def testEditPost(request, postId):
    acc = Account.objects.get(user_ptr=request.user)
    user = Sharer.objects.get(account=acc) if acc.role=='sharer' else Manager.objects.get(account=acc) 
    if request.method == 'GET':
        post = Post.objects.get(id=postId)
        img = post.image_set.all()
        form_img = []
        a = 0
        for i in img :
            a = a + 1
            form_img.append(CreateImgForm(instance=i, prefix=f'form-{a}'))
        context = {
            'user': user,
            'post': post,
            'img': img,
            'form_img': form_img,
            'provider': Manager.objects.all()
        }
        return render(request, 'posts/edit_post.html', context)
    elif request.method == 'POST':
        post = Post.objects.get(id=postId)
        post.title = request.POST.get('title_post')
        post.content = request.POST.get('content_post')
        if request.POST.get('provider_post') != 'None':
            post.provider_id = request.POST.get('provider_post')
        else:
            post.provider_id = None
        img = post.image_set.all()

settingspage/templates/posts/add_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tạo bài viết</title>
    <link rel="stylesheet" href="{% static 'AddPost.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

<form method="post" action="{% url 'settingspage:testCreatePosts' %}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="maincontainer">
        <div class="content">
            <h1 id="title">Tạo bài viết</h1>
            <div class="info">
                <img src="{{user.avatar.url}}" alt="image" width="70px" height="70px">
                <h3 class="name"> {{user.name}}</h3>
                <p>Time: {{time}}</p>
                <p>Đang ở:
                  <select name="provider_post" id="provider_post">
                      {% for pro in provider %}
                      <option  value="{{pro.account_id}}">{{pro.name}}</option>
                      {% endfor %}
                      <option selected value="None">None</option>
                  </select>
                </p>
                
                <i class="fa-solid fa-location-dot"></i>
                <select  class="form-select form-select-sm mb-3" id="city" name="city" aria-label=".form-select-sm" required>
                    <option value="" selected>Chọn tỉnh thành</option>           
                    </select>
                              
                    <select class="form-select form-select-sm mb-3" id="district" name="district" aria-label=".form-select-sm" required>
                    <option value="" selected>Chọn quận huyện</option>
                    </select>
                    
                    <select class="form-select form-select-sm" id="ward" name="ward" aria-label=".form-select-sm" required>
                    <option value="" selected >Chọn phường xã</option>
                </select>
                <h3><input required id="title_post" name="title_post" type="text" placeholder="Nhập tiêu đề" class="tieude"></h3>
                <textarea required id="content_post" name="content_post"  cols="78" rows="15" placeholder="Nhập nội dung vào đây nhé"></textarea>
                <p>Chọn ảnh:</p>
                <input type="file" name="images" id="images" multiple>
                <div class="submit">
                <button type="submit" onclick="showNotification()">Submit</button>
                <a href="{% url 'settingspage:testPostPage' %}"><button type="button" id="cancel">Cancel</button></a>
                </div>
                
            
            </div>
        </div>
    </div>
</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script>
    var citis = document.getElementById("city");
    var districts = document.getElementById("district");
    var wards = document.getElementById("ward");
    var Parameter = {
      url: "https://raw.githubusercontent.com/kenzouno1/DiaGioiHanhChinhVN/master/data.json", 
      method: "GET", 
      responseType: "application/json", 
    };
    var promise = axios(Parameter);
    promise.then(function (result) {
      renderCity(result.data);
    });

    function renderCity(data) {
      for (const x of data) {
        citis.options[citis.options.length] = new Option(x.Name, x.Id);
      }
      citis.onchange = function () {
        district.length = 1;
        ward.length = 1;
        if(this.value != ""){
          const result = data.filter(n => n.Id === this.value);

          for (const k of result[0].Districts) {
            district.options[district.options.length] = new Option(k.Name, k.Id);
          }
        }
      };
      district.onchange = function () {
        ward.length = 1;
        const dataCity = data.filter((n) => n.Id === citis.value);
        if (this.value != "") {
          const dataWards = dataCity[0].Districts.filter(n => n.Id === this.value)[0].Wards;

          for (const w of dataWards) {
            wards.options[wards.options.length] = new Option(w.Name, w.Id);
          }
        }
      };
    }
</script>
</body>
</html>

settingspage/templates/posts/edit_post.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tạo bài viết</title>
    <link rel="stylesheet" href="{% static 'AddPost.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
<form method="post" action="{% url 'settingspage:testEditPost' post.id%}" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="maincontainer">
        <div class="content">
            <h1 id="title">Chỉnh sửa bài viết</h1>
            <div class="info">
                <img src="{{user.avatar.url}}" alt="image" width="70px" height="70px">
                <h3 class="name"> <strong>{{user.name}}</strong></h3>
                <p>Time: {{post.time}}</p>
                <p>Đang ở:
                    <select name="provider_post" id="provider_post">
                        {% for pro in provider %}
                        <option  value="{{pro.account_id}}">{{pro.name}}</option>
                        {% endfor %}
                        <option selected value="None">None</option>
                    </select>
                </p>
                
                <i class="fa-solid fa-location-dot"></i>

                <select  class="form-select form-select-sm mb-3" id="city" name="city" aria-label=".form-select-sm" required>
                <option value="{{post.city}}" selected>{{post.city}}</option>           
                </select>
                            
                <select class="form-select form-select-sm mb-3" id="district" name="district" aria-label=".form-select-sm" required>
                <option value="{{post.district}}" selected>{{post.district}}</option>
                </select>
                
                <select class="form-select form-select-sm" id="ward" name="ward" aria-label=".form-select-sm" required>
                <option value="{{post.ward}}" selected >{{post.district}}</option>
                </select>
                <h4><input required id="address_post" name="address_post" placeholder="Nhập nhập địa chỉ cụ thể" class="tieude" value="{{post.address}}"></h4>
                
                <h3><input required id="title_post" name="title_post" type="text" placeholder="Nhập tiêu đề" class="tieude" value="{{post.title}}"></h3>
                <textarea  required id="content_post" name="content_post"  cols="78" rows="15" placeholder="Nhập nội dung vào đây nhé">{{post.content}}</textarea>
                {% for form in form_img %}
                {% if form.instance.isDelete == False %} 
                <div style="background-color: aliceblue;" class="paragraph-container">
              
                    <div style="display: flex;">
                    <img width="100px" height="100px" src="{{form.instance.img.url}}" alt="" id="{{form.prefix}}">
                    <div>
                        <p style="color: blue; font-weight: bold; font-size: 20px; ">Change: </p>
                        <input type="file" name="{{form.prefix}}-img" accept="image/*" id="id_{{form.prefix}}-img" onchange="setImage({{form.prefix}})">
                    </div>
                     {% if form.instance.isDelete == False%}
                    <a href="{% url 'settingspage:testDeleteImagePost' post.id form.instance.id %}" onclick="deleteImagePost({{post.id}}, {{form.instance.id}})" style="color: red; font-weight: bold; text-decoration: none; font-size: large;" ><i style="font-size: 30px; margin-top: 40px;" class="fas fa-trash" ></i></a>
                    {% endif %}
                    </div>
                    
                   
                    
                </div>
                {% endif %}
                {% endfor %}
                <p>Chọn ảnh:</p>
                <input type="file" name="images" id="images" multiple>
                <div class="submit">
                <button type="">Submit</button>
                <a href="{% url 'settingspage:testRecoverDelete' post.id %}"><button type="button" id="cancel">Cancel</button></a>
                </div>
            </div>
        </div>
    </div>
</form>
<script>
    // xử lí hiện thị lựa chọn provider nào 
    defaultValue = "{{post.provider_id}}";
    var dataSelector = document.getElementById('provider_post');
    var defaultOption = dataSelector.querySelector('option[value="' + defaultValue + '"]');
    if (defaultOption) {
        defaultOption.selected = true;
    }
    // hàm xử lí show hình ảnh khi thay đổi hình ảnh 
    function setImage(imageId) {
        var elementId = 'id_' + imageId + '-img';

        var input = document.getElementById(elementId);
        var image = document.getElementById(imageId);
        var selectedFile = input.files[0];
        if (selectedFile) {
            const reader = new FileReader();
            reader.onload = function(e) {
              image.src = e.target.result;
            };
            reader.readAsDataURL(selectedFile);
        }
    }

    function deleteImagePost(postId, imageId) {
      $.ajax({
        url: `/posts/edit/${postId}/testDeleteImagePost/${imageId}/`,
        type: 'GET',
        dataType: 'json',
        success: function(data) {

        },
        error: function(xhr, status, error) {
            console.error('AJAX Error:', status, error);
        }

      });
    }

</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script>
    var citis = document.getElementById("city");
    var districts = document.getElementById("district");
    var wards = document.getElementById("ward");
    var Parameter = {
      url: "https://raw.githubusercontent.com/kenzouno1/DiaGioiHanhChinhVN/master/data.json", 
      method: "GET", 
      responseType: "application/json", 
    };
    var promise = axios(Parameter);
    promise.then(function (result) {
      renderCity(result.data);
    });

    function renderCity(data) {
      for (const x of data) {
        citis.options[citis.options.length] = new Option(x.Name, x.Id);
      }
      citis.onchange = function () {
        district.length = 1;
        ward.length = 1;
        if(this.value != ""){
          const result = data.filter(n => n.Id === this.value);

          for (const k of result[0].Districts) {
            district.options[district.options.length] = new Option(k.Name, k.Id);
          }
        }
      };
      district.onchange = function () {
        ward.length = 1;
        const dataCity = data.filter((n) => n.Id === citis.value);
        if (this.value != "") {
          const dataWards = dataCity[0].Districts.filter(n => n.Id === this.value)[0].Wards;

          for (const w of dataWards) {
            wards.options[wards.options.length] = new Option(w.Name, w.Id);
          }
        }
      };
    }
</script>
</body>
</html>

settingspage/templates/posts/postList.html
{% extends "../settingspage/base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'posts/styles.css'%}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock css %}

{% block post%} 
<h1 style="text-align: center; margin-top: 50px;">Bài viết của bạn</h1>
<ul>
    {% for post in postList %}
    
    <li id="post_{{post.id}}">
        <div class="date">
            <h2>{{post.time.date}}</h2>
        </div>
        <div class="info">
            <div class="time">
                <i class="fa-solid fa-clock"></i>
                <p>{{post.time.time}}</p>
            </div>
            <div class="shop">
                <i class="fa-solid fa-shop"></i>
                <a href="#"><p>{{post.provider.name}}</p></a>
            </div>
            <div class="location">
                <i class="fa-solid fa-location-dot"></i>
                <a href="#"><p>{{post.ward}} - {{post.district}} - {{post.city}} <br>({{post.address}})</p></a>
            </div>
            <div class="title">
                <i class="fa-solid fa-bars-staggered"></i>
                <h2> <small>Tiêu đề: </small> {{post.title}}</h2>
            </div>
            <div class="likedis">
                <i class="fa-solid fa-thumbs-up"></i> <p>{{post.like}}</p>
                <i class="fa-solid fa-comment"></i> <p>{{post.commentNum}}</p>
            </div>
            <div class="action-product">
                <a class="edit-product" href="{% url 'settingspage:testEditPost' post.id %}">
                    <div>
                        <i class="fa-solid fa-pen" aria-hidden="true"></i>
                    </div>
                </a>
                <a class="delete-product" onclick="deletePost(event, {{post.id}})">
                    <div>
                        <i class="fa-solid fa-trash" aria-hidden="true"></i>
                    </div>
                </a>
            </div>
             
        </div>
    </li>
    {% endfor %}

</ul>
<a href="{% url 'settingspage:testCreatePosts' %}" class="add-product">
    <div class="container-add-product">
        <i class="fa-solid fa-circle-plus"></i>
        <h3>Thêm bài viết</h3>
    </div>
</a>

<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script>
    function deletePost(event, postId){
        var userChoice = window.confirm("Bạn có chắc muốn xóa bài viết không?");
        if( userChoice){
            $.ajax({
                url: `/settings/posts/delete/${postId}/`,  // Điều chỉnh đúng đường dẫn của view xóa dữ liệu
                type: 'POST',
                success: function(response) {
                    var containerPost = document.getElementById('post_' + postId);
                    if(response.success === true){
                        containerPost.remove()
                        alert("Xóa bài viết thành công")
                    }

                },
                error: function(error) {
                    console.log(error);
                }
            });
        }
    }
</script>
{% endblock %}