bkvivu/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from profilepage import views as profileViews
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('homepage/')),
    path('admin/', admin.site.urls),
    path('logout/', profileViews.logout_view, name = 'logout'),
    path('homepage/', include('homepage.urls')),
    path('postspage/', include('postspage.urls')),
    path('profile/', include('profilepage.urls')),
    path('settings/', include('settingspage.urls')),
    path('shoppingcart/', include('shoppingcart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('login/', views.loginPage, name='loginPage'),
    path('login/register/', views.registerPage, name='registerPage'),
    path('update_likes/<int:post_id>/', views.update_likes, name='update_likes'),

    path('searchTag/<str:tag>/', views.searchTag, name='searchTag'),
    path('search/', views.mainSearch, name='mainSearch'),
]

postspage/urls.py
from django.urls import path, include
from . import views

# 3/12
from django.conf import settings
from django.conf.urls.static import static

app_name = 'postspage'
urlpatterns = [
    path('', views.postsPage, name='postsPage'),
    path('posts/', views.postsView, name='posts'),
    
    path('restaurants/', views.restaurantsView, name='restaurants'),
    path('update_likes/<int:post_id>/', views.update_likes, name='update_likes'),
    path('insert_comment/<int:post_id>/', views.insert_comment, name='insert_comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='insert_comment'),
    path('get_comments/<int:post_id>/', views.get_comments, name='get_comments'),
    path('search/', views.searchPosts, name='search_post'),
    path('search/detail/<int:post_id>/', views.detailPost, name='detail_post'),
    # path('test', views.test, name='test')
]   + static(settings.MEDIA_URL, document_root = settings.MEDIA_URL) # 3/12

profilepage/urls.py
from django.urls import path, include
from . import views

app_name = 'profilepage'
urlpatterns = [
    path('<int:acc_id>/', views.profilePage, name='profilePage'),
    path('logout/', views.logout_view, name='logoutPage'),
    path('<int:acc_id>/vote', views.voteProfile, name='voteProfile'),
    path('<int:acc_id>/chatDefault', views.chatPageDefault, name='chatDefault'),
    path('<int:acc_id>/chat/<int:user_id>/', views.chatPage, name='chatPage'),
    path('<int:acc_id>/chat/<int:user_id>/save', views.save_message, name='saveMessage'),
    path('<int:acc_id>/chat/<int:user_id>/get', views.get_message, name='getMessage'),
]

settingspage/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'settingspage'
urlpatterns = [
    path('', views.settingsPage, name='settingsPage'),
    path('general/', views.generalPage, name='gerenalPage'),

    path('posts', views.testPostPage, name='testPostPage'),
    path('posts/addPosts', views.testCreatePosts, name='testCreatePosts'),
    path('posts/delete/<int:postId>/', views.testDeletePost, name='testDeletePost'),
    path('posts/edit/<int:postId>/', views.testEditPost, name="testEditPost"),
    path('posts/edit/<int:postId>/testDeleteImagePost/<int:imageId>', views.testDeleteImagePost, name='testDeleteImagePost'),
    path('posts/edit/<int:postId>/testRecoverDelete/', views.testRecoverDelete, name="testRecoverDelete"),

    path('product/', views.ProductManager, name='product'),
    path('product/add', views.CreateProduct.as_view(), name='addProduct'),
    path('product/delete/<int:product_id>', views.deleteProduct, name='deleteProduct'),
    path('product/edit/<int:product_id>', views.editProduct.as_view(), name='editProduct'),


    path('bills/', views.billsPage, name='billsPage'),
    path('bills/viewBill/<int:billId>', views.viewBill, name='viewBill'),
    path('bills/viewBill/<int:billId>/accept/>', views.accept, name='accept'),
    path('bills/viewBill/<int:billId>/decline/>', views.decline, name='decline'),


    path('statistics/', views.statisticsPage, name='statisticsPage'),

    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_URL)

shoppingcart/urls.py
from django.urls import path, include
from . import views

app_name = 'shoppingcart'
urlpatterns = [
    path('', views.viewShoppingCart, name ='shoppingCart'),
    path('update_quantity/', views.updateQuantity, name='updateQuantity'),
    path('create_bill/', views.createBill, name='createBill'),
    path('payment/<int:bill_id>/', views.Payment.as_view(), name='paymentPage'),
    path('cancelpayment/<int:bill_id>/', views.cancelPayment, name = 'cancelPayment'),
    path('timeoutpayment/<int:bill_id>/', views.timeoutPayment, name = 'timeoutPayment'),
    path('orderlist/', views.OrderList.as_view(), name= 'orderList'),
    path('addToCart/', views.addToCart, name='addItem'),

]

shoppingcart/models.py
from django.db import models

# Create your models here.

shoppingcart/forms.py
from django import forms
from homepage.models import *

class BillForm(forms.ModelForm):
    class Meta:
        model = Bill
        fields = ('img', )

shoppingcart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.views import View
from django.views.decorators.csrf import csrf_exempt
import json
from collections import OrderedDict

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib.auth import logout
from collections import defaultdict
from .models import *
from .forms import *
from homepage.models import *
from django.utils import timezone


#Shopping Cart
def viewShoppingCart(request):
    if request.user.is_authenticated:
        #Tài khoản đang đăng nhập hệ thống
        acc = Account.objects.get(user_ptr=request.user)
        user_cart_items = CartItem.objects.filter(account= acc).order_by('-id')
        #Tạo danh sách products theo cửa hàng
        items_in_cart = dict()
        for item in user_cart_items:
            manager = item.product.provider  # Thay 'manager' bằng trường hoặc liên kết mà bạn sử dụng để chỉ đến Manager
            if manager in items_in_cart.keys():
                items_in_cart[manager].append(item)
            else:
                items_in_cart[manager] = [item,]

        context = {
            'acc': acc,
            'user': Manager.objects.get(account=acc) if acc.role == 'manager' else Sharer.objects.get(account=acc),
            'items_in_cart' : items_in_cart,
        }
        return render(request, 'shoppingcart/shoppingCart.html', context)
    else :
        messages.error("Bạn cần đăng nhập để thực hiện thao tác này")
        return redirect('homepage:loginPage')

# Cập nhật, xóa dữ liệu sản phẩm trong giỏ hàng
@csrf_exempt
def updateQuantity(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        item_id = data.get('item_id')
        action = data.get('action')
        # Lấy đối tượng ItemCart từ cơ sở dữ liệu
        item = CartItem.objects.get(pk=item_id)

        if action == 'increase':
            item.quantity += 1
            item.save()
        elif action == 'decrease':
            item.quantity -= 1 if item.quantity > 0 else 0
            item.save()
        elif action == 'removeitem':
            item.delete()

        return JsonResponse({'message': 'Số lượng đã được cập nhật'})
    else:
        return JsonResponse({'error': 'Invalid request method'})

# Tạo hóa đơn thanh toán
def createBill(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        #Dữ liệu các id của các lựa chọn trong giỏ hàng
        item_ids = data.get('selectedItems')
        manager_id = int(data.get('manager_id'))
        manager = CartItem.objects.get(pk = item_ids[0]).product.provider
        # Tạo đối tượng Bill
        new_bill = Bill.objects.create(
            acc = Account.objects.get(user_ptr=request.user),
            provider = manager,
            time = timezone.now()
        )
        # Tạo order cho mỗi items
        for item_id in item_ids:
            item = CartItem.objects.get(pk = item_id)
            _product = item.product
            _quantity = item.quantity
            if _product.provider.account.id == manager_id:
                item.delete()
                new_bill.price += _product.price * _quantity
                print(new_bill.price)
                new_order = Order.objects.create(
                    bill = new_bill,
                    product = _product,
                    quantity = _quantity
                )
        #Lưu lại giá
        new_bill.save()
        return JsonResponse({'bill_id': new_bill.id ,'messages': 'Tạo bill thành công'})

    else :
        print("thất bại")
        return JsonResponse({'error': 'Tạo bill thất bại'})

#Hiển thị trang thanh toán
class Payment(View):
    def get(self, request, bill_id):
        acc = Account.objects.get(user_ptr = request.user)
        bill = Bill.objects.get(pk = bill_id)
        manager = bill.provider
        form_pay = BillForm(instance= bill)
        # Thời hạn thanh toán còn lại
        time_remaining = int(((bill.time + timezone.timedelta(minutes=10)) - timezone.now()).total_seconds())
        context = {
            'acc' : acc,
            'user': Manager.objects.get(account=acc) if acc.role == 'manager' else Sharer.objects.get(account=acc),
            'bill' : bill,
            'form_pay' : form_pay,
            'manager' : manager,
            'time_remaining' : time_remaining
        }
        return render(request, 'shoppingcart/paymentPage.html', context)
    def post(self, request, bill_id):
        acc = Account.objects.get(user_ptr = request.user)
        bill = Bill.objects.get(pk = bill_id)
        manager = bill.provider
        form_pay = BillForm(request.POST, request.FILES, instance= bill)
        if form_pay.is_valid():
            form_pay.save()
        context = {
            'acc' : acc,
            'bill' : bill,
            'form_pay' : form_pay,
            'manager' : manager
        }
        return redirect('shoppingcart:orderList')

# Xóa bill và các order liên quan ở database
def cancelPayment(request, bill_id):
    bill = Bill.objects.get(pk = bill_id)
    bill.status = "DeclineByUser"
    bill.save()
    return redirect('shoppingcart:orderList')

def timeoutPayment(request, bill_id):
    bill = Bill.objects.get(pk = bill_id)
    bill.status = "Timeout"
    bill.save()
    return redirect('shoppingcart:orderList')

# Xem danh sách đơn hàng đã đặt
class OrderList(View):
    def get(self, request):
        if request.user.is_authenticated:
            _acc = Account.objects.get(user_ptr=request.user)
            listbills = Bill.objects.filter(acc = _acc).order_by('-time')
            for bill in listbills:
                # Kiểm tra nếu bill không có img và đã quá 10 phút
                if not bill.img and (timezone.now() - bill.time).total_seconds() > 600:
                    bill.status = "Timeout"
                    bill.save()
            productsOfBill = OrderedDict()
            for _bill in listbills:
                orders = Order.objects.filter(bill = _bill)
                productsOfBill[_bill] = []
                for order in orders:
                    productsOfBill[_bill].append(order)


            context = {
                'acc' : _acc,
                'user': Manager.objects.get(account=_acc) if _acc.role == 'manager' else Sharer.objects.get(account=_acc),
                'productOfBill' : productsOfBill
            }
            return render(request, "shoppingcart/orderlist.html", context)
        else:
            return redirect('homepage:loginPage')
    def post(self, request):
        pass
        return HttpResponse("Post Orderlist")
 
@csrf_exempt
def addToCart(request):
    if request.method == "POST":
        itemId = request.POST.get('itemId')
        print(itemId)
        # acc, user : Bản thân người đang đăng nhập
        acc = Account.objects.get(user_ptr=request.user)
        product = Product.objects.get(pk = itemId)

        # Lấy (Tạo) cartItem
        cart_item, created = CartItem.objects.get_or_create(account=acc, product=product)
        if not created:
            cart_item.quantity += 1
            cart_item.save()
        return JsonResponse({'success': True})

shoppingcart/templates/shoppingcart/orderlist.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Danh sách đơn hàng</title>
  <script src="https://kit.fontawesome.com/bc4d8a1311.js" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="{% static 'headerStyle.css' %}">
  <link rel="stylesheet" href="{% static 'orderlistStyle.css' %}">
  <script src="{% static 'orderlistScript.js' %}"></script>
</head>
<body>
  <!-- Header -->
  <div class="header" style="padding: 0px 35px;">
    <div class="left">
        <a href="{% url 'homepage:homePage' %}" class="logo">
            <img src="{% static 'images/logo.png' %}"  alt="logo">
            <div class = "description">
                <h2><strong>BKvivu</strong></h2>
                <p style="width: 400px;">Nền tảng chia sẻ dịch vụ hàng đầu</p>
            </div> 
        </a>
    </div>
        
    <div class="right">
        <div id="-box-nav">
            <a href="{% url 'postspage:posts' %}" id="community"><i class="fa fa-fw fa-users"></i>Khám phá</a>
            <div class="subnav">
                <a href="{% url 'postspage:restaurants' %}">Cửa hàng</a>
                <a href="{% url 'postspage:posts' %}">Bài chia sẻ</a>
            </div>
        </div>
        {% if acc.role == 'sharer' %}
          <div class="setting_icon">
              <a href="{% url 'shoppingcart:shoppingCart'  %}" class="setting">
                  <div >
                      <i class="fa-solid fa-cart-shopping"></i>
                  <span>Cart</span>
                  </div>
              </a>
          </div>
          {% endif %}
        <div class="setting_icon">
            <a href="{% url 'settingspage:settingsPage' %}" class="setting">
                <div >
                <i class="fa-solid fa-gear"></i>
                <span>Settings</span>
                </div>
            </a>
        </div>
        <div class="setting_icon">
            <a href="/logout/" class="setting">
                <div>
                    <i class="fa-solid fa-arrow-right-from-bracket"></i>
                <span>Logout</span>
                </div>
            </a>
        </div>
        <a href="{% url 'profilepage:profilePage' acc.id%}" class="logo-user" style="width: auto;">
            <img class="img-user" src = "{{user.avatar.url}}"/>
        </a>
        
    </div>
</div>
{% comment %} Vòng for duyệt tất cả các đơn hàng {% endcomment %}
    {% for bill, orders in productOfBill.items %}
    <div class="order-container">
        <div class="order-header">
          <div class="store-info">
            <div class="avatar-manager">
              <img src="{{bill.provider.avatar.url}}" alt="{{bill.provider.name}}">
            </div>
            <div>
              <h3>{{bill.provider.name}}</h3>
            </div>
          </div>
          <div class="order-status">
            {% if bill.status == "Waiting" %}
                <h4 class="pending">Chờ xác nhận</h4>
            {% elif bill.status == "Timeout" %}
              <h4 class="cancelled">Quá hạn thanh toán</h4>
            {% elif bill.status == "DeclineByUser" %}
                <h4 class="cancelled">Đã hủy</h4>
            {% elif bill.status == "Decline" %}
                <h4 class="cancelled">Bị từ chối</h4>
            {% else %}
                <h4 class="paid">Đã xác nhận</h4>
            {% endif %}
          </div>
        </div>
        {% for order in orders %}
        <!-- Sản phẩm 1 -->
        <div class="product-item">
          <img src="{{order.product.img.url}}" alt="{{order.product.name}}">
          <div class="product-details">
            <h4>{{order.product.name}}</h4>
            <p>Giá: {{order.product.price}} VNĐ</p>
          </div>
          <div class="product-quantity">Số lượng: {{order.quantity}}</div>
        </div>
        {% endfor %}

        <!-- Khối tổng tiền và nút thanh toán, hủy đơn -->
        <div class="order-total">
          <div>Tổng Tiền: {{bill.price}} VNĐ</div>
          {% if bill.status == "Waiting" %}
            <div class="action-buttons">
              {% if not bill.img %}
              <!--người dùng chưa thực hiện thanh toán-->
              <button onclick="payOrder({{bill.id}})">Thanh Toán</button>
              {% else %}
              <h4 class="paid">Đã thanh toán</h4>
              {% endif %}
              <button onclick="cancelOrder({{bill.id}})">Hủy Đơn</button>
            </div>
          {% endif %}
        </div>
    </div>
    {% endfor %}

    
    <!-- Footer -->
    <footer class="footer">
      <div class="waves">
        <div class="wave" id="wave1"></div>
        <div class="wave" id="wave2"></div>
        <div class="wave" id="wave3"></div>
        <div class="wave" id="wave4"></div>
      </div>
      <ul class="social-icon">
        <li class="social-icon__item"><a class="social-icon__link" href="#">
            <ion-icon name="logo-facebook"></ion-icon>
          </a></li>
        <li class="social-icon__item"><a class="social-icon__link" href="#">
            <ion-icon name="logo-twitter"></ion-icon>
          </a></li>
        <li class="social-icon__item"><a class="social-icon__link" href="#">
            <ion-icon name="logo-linkedin"></ion-icon>
          </a></li>
        <li class="social-icon__item"><a class="social-icon__link" href="#">
            <ion-icon name="logo-instagram"></ion-icon>
          </a></li>
      </ul>
      <ul class="menu">
        <li class="menu__item"><a class="menu__link" href="#">Home</a></li>
        <li class="menu__item"><a class="menu__link" href="#">About</a></li>
        <li class="menu__item"><a class="menu__link" href="#">Services</a></li>
        <li class="menu__item"><a class="menu__link" href="#">Team</a></li>
        <li class="menu__item"><a class="menu__link" href="#">Contact</a></li>

      </ul>
      <p>&copy;2023 BKvivu | BaoDungDatDatThanhTruong</p>
  </footer>
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>

shoppingcart/templates/shoppingcart/shoppingCart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Shopping Cart</title>
  <link rel="stylesheet" href="{% static 'headerStyle.css' %}">
  <link rel="stylesheet" href="{% static 'shoppingCartStyle.css' %}">
  <script src="https://kit.fontawesome.com/bc4d8a1311.js" crossorigin="anonymous"></script>
  <script src="{% static 'shoppingCartScript.js' %}"></script>
</head>
<body onload="updateTotal()">
<!-- Header -->
<div class="header" style="padding: 0px 35px;">
  <div class="left">
      <a href="{% url 'homepage:homePage' %}" class="logo">
          <img src="{% static 'images/logo.png' %}"  alt="logo">
          <div class = "description">
              <h2><strong>BKvivu</strong></h2>
              <p style="width: 400px;">Nền tảng chia sẻ dịch vụ hàng đầu</p>
          </div> 
      </a>
  </div>
      
  <div class="right">
      <div id="-box-nav">
          <a href="{% url 'postspage:posts' %}" id="community"><i class="fa fa-fw fa-users"></i>Khám phá</a>
          <div class="subnav">
              <a href="{% url 'postspage:restaurants' %}">Cửa hàng</a>
              <a href="{% url 'postspage:posts' %}">Bài chia sẻ</a>
          </div>
      </div>
      {% if acc.role == 'sharer' %}
            <div class="setting_icon">
                <a href="{% url 'shoppingcart:shoppingCart'  %}" class="setting">
                    <div >
                        <i class="fa-solid fa-cart-shopping"></i>
                    <span>Cart</span>
                    </div>
                </a>
            </div>
            {% endif %}
      <div class="setting_icon">
          <a href="{% url 'settingspage:settingsPage' %}" class="setting">
              <div >
              <i class="fa-solid fa-gear"></i>
              <span>Settings</span>
              </div>
          </a>
      </div>
      <div class="setting_icon">
          <a href="/logout/" class="setting">
              <div>
                  <i class="fa-solid fa-arrow-right-from-bracket"></i>
              <span>Logout</span>
              </div>
          </a>
      </div>
      <a href="{% url 'profilepage:profilePage' acc.id%}" class="logo-user" style="width: auto;">
          <img class="img-user" src = "{{user.avatar.url}}"/>
      </a>
      
  </div>
</div>
  {% comment %} Giỏ hàng {% endcomment %}
  <div id="cart">
    <h1>Giỏ Hàng</h1>
    <!-- Vòng lặp for qua từng cửa hàng-->
    {% if items_in_cart.items %}
    {% for manager, items in items_in_cart.items %}
      <div class="store">
        <a class="manager-name" href="{% url 'profilepage:profilePage' manager.account.id%}">
          <h2>{{manager.name}}</h2>
        </a>
        {% for item in items %}
        <!-- Sản phẩm -->
          <div class="product">
            <input type="checkbox" class="checkbox" data-item-id="{{ item.id }}" onclick="updateTotal()">
            <img src="{{item.product.img.url}}" alt="{{item.product.name}}">
            <div class="product-info">
              <h3>{{item.product.name}}</h3>
              <p class="price">{{item.product.price}}</p>
            </div>
            <div class="quantity">
              <button onclick="decreaseQuantity(this)" data-item-id="{{ item.id }}">-</button>
              <span class="quantity-value">{{item.quantity}}</span>
              <button onclick="increaseQuantity(this)" data-item-id="{{ item.id }}">+</button>
            </div>
            <div class="subtotal-container">
              <div class="subtotal-price">{{item.product.price}}</div>
            </div>
            <button class="remove-btn" onclick="removeProduct(this)" data-item-id="{{ item.id }}">X</button>
          </div>
        {% endfor %}
        <!-- Giá tiền -->
        <div class="store-footer">
          <form class="order-form" method="POST" action="{% url 'shoppingcart:createBill' %}">
            {% csrf_token %}
            <input type="hidden" name="manager_id" value="{{ manager.account.id }}">
            <input type="hidden" name="selectedItems" value="">
            <div class="store-total">Total: 0 VNĐ</div>
            <button class="order-btn">Đặt hàng</button>
          </form>
        </div>
      </div>
    {% endfor %}
    {% else %}
    <h3>Bạn chưa thêm sản phẩm nào vào giỏ hàng!!!</h3>
    {% endif %}
  </div>

  <div class="order-list">
    <a href="{% url 'shoppingcart:orderList'%}">Đơn Hàng Đã Đặt</a>
  </div>

    <!-- Footer -->
    <footer class="footer">
      <div class="waves">
        <div class="wave" id="wave1"></div>
        <div class="wave" id="wave2"></div>
        <div class="wave" id="wave3"></div>
        <div class="wave" id="wave4"></div>
      </div>
      <ul class="social-icon">
        <li class="social-icon__item"><a class="social-icon__link" href="#">
            <ion-icon name="logo-facebook"></ion-icon>
          </a></li>
        <li class="social-icon__item"><a class="social-icon__link" href="#">
            <ion-icon name="logo-twitter"></ion-icon>
          </a></li>
        <li class="social-icon__item"><a class="social-icon__link" href="#">
            <ion-icon name="logo-linkedin"></ion-icon>
          </a></li>
        <li class="social-icon__item"><a class="social-icon__link" href="#">
            <ion-icon name="logo-instagram"></ion-icon>
          </a></li>
      </ul>
      <ul class="menu">
        <li class="menu__item"><a class="menu__link" href="#">Home</a></li>
        <li class="menu__item"><a class="menu__link" href="#">About</a></li>
        <li class="menu__item"><a class="menu__link" href="#">Services</a></li>
        <li class="menu__item"><a class="menu__link" href="#">Team</a></li>
        <li class="menu__item"><a class="menu__link" href="#">Contact</a></li>

      </ul>
      <p>&copy;2023 BKvivu | BaoDungDatDatThanhTruong</p>
  </footer>
  <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
  <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>