bkvivu/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from profilepage import views as profileViews
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('homepage/')),
    path('admin/', admin.site.urls),
    path('logout/', profileViews.logout_view, name = 'logout'),
    path('homepage/', include('homepage.urls')),
    path('postspage/', include('postspage.urls')),
    path('profile/', include('profilepage.urls')),
    path('settings/', include('settingspage.urls')),
    path('shoppingcart/', include('shoppingcart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profilepage/urls.py
from django.urls import path, include
from . import views

app_name = 'profilepage'
urlpatterns = [
    path('<int:acc_id>/', views.profilePage, name='profilePage'),
    path('logout/', views.logout_view, name='logoutPage'),
    path('<int:acc_id>/vote', views.voteProfile, name='voteProfile'),
    path('<int:acc_id>/chatDefault', views.chatPageDefault, name='chatDefault'),
    path('<int:acc_id>/chat/<int:user_id>/', views.chatPage, name='chatPage'),
    path('<int:acc_id>/chat/<int:user_id>/save', views.save_message, name='saveMessage'),
    path('<int:acc_id>/chat/<int:user_id>/get', views.get_message, name='getMessage'),
]

profilepage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib import messages

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib.auth import logout
from .models import *
from homepage.models import *


# Create your views here.
def profilePage(request, acc_id):
    if not request.user.is_authenticated:
        return redirect('homepage:loginPage')
    # target_acc , target_user : đối tượng mà mình vào xem trang cá nhân
    target_acc = Account.objects.get(pk=acc_id)
    target_user = Sharer.objects.get(account= target_acc) if target_acc.role == 'sharer' else Manager.objects.get(account= target_acc)
    # acc, user : Bản thân người đang đăng nhập
    acc = Account.objects.get(user_ptr=request.user)
    user = Sharer.objects.get(account= acc) if acc.role == 'sharer' else Manager.objects.get(account= acc)
    # Lấy số sao đã vote của người đăng nhập nếu profile đang xem là Manager
    starsvotetarget = 5
    if(target_acc.role == 'manager') and (target_acc.id != acc.id):
        try:
            voteobj = StarVote.objects.get(account=acc, manager= target_user)
            starsvotetarget = voteobj.stars
        except:
            pass
    # Danh sách những bài viết mà người dùng đã like
    listPosts = Post.objects.filter(account = target_acc).order_by('-time')
 
    listPostsLike = []
    for _posts in listPosts:
        if UserLike.objects.filter(account= acc, post = _posts):
            listPostsLike.append(_posts)
    context = {
        'acc': acc,
        'target_user': target_user,
        'user': user,
        'starsvotetarget': starsvotetarget,
        'listPosts': listPosts,
        'listPostsLike' : listPostsLike
    }
    return render(request, 'profile.html', context)

#vote Profile manager
def voteProfile(request,acc_id):
    if request.method == 'POST':
        try:
            acc = Account.objects.get(user_ptr=request.user)
            target_user=Manager.objects.get(account= acc_id)
            stars = request.POST.get("rate")
            # Lấy hoặc tạo một đối tượng StarVote dựa trên account_id và manager_id
            star_vote, created = StarVote.objects.get_or_create(
                account = acc,
                manager = target_user,
                defaults={'stars': stars}  # Điền vào giá trị mặc định cho số sao nếu đối tượng chưa tồn tại
            )
            if not created:
            # Đối tượng đã tồn tại, bạn có thể thực hiện các thay đổi tùy thuộc vào trường hợp của bạn
                star_vote.stars = stars
                star_vote.save()
            target_user.save() #Cập nhật rank cho người quản lý
        except:
            pass
    else:
        pass
    return redirect('profilepage:profilePage', acc_id=acc_id)

# Log out button
def logout_view(request):
    if not request.user.is_authenticated:
        return redirect('homepage:loginPage')
    logout(request)
    return redirect('homepage:homePage')



#Chat
def chatPageDefault(request, acc_id):
    if request.method == 'GET':
        acc1 = Account.objects.get(user_ptr=request.user)
        user1 = Sharer.objects.get(account= acc1) if acc1.role == 'sharer' else Manager.objects.get(account= acc1)

        all_user = Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('receiver').exclude(receiver=acc1.id).distinct() if acc1.role == 'manager' else Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('sender').exclude(sender=acc1.id).distinct()

        #default : tuong tac 2 chieu roi, i send you , you send me
        list_all_user = []
        for user in all_user:
            add_user = Manager.objects.get(pk=user['sender']) if acc1.role == 'sharer' else Sharer.objects.get(pk=user['receiver'])
            list_all_user.append(add_user)

        context = {
            'acc_id': acc_id,
            'user1' : user1,
            'all_user': list_all_user
        }
        return render(request, "chat/chat_base.html", context)
    
def chatPage(request, acc_id, user_id):
    if request.method == 'GET':
        acc1 = Account.objects.get(user_ptr=request.user)
        acc2 = Account.objects.get(id = user_id)
        user1 = Sharer.objects.get(account= acc1) if acc1.role == 'sharer' else Manager.objects.get(account= acc1)
        user2 = Sharer.objects.get(account= acc2) if acc2.role == 'sharer' else Manager.objects.get(account= acc2)
        # check if user2 has conversation with user1, if not initialize it
        all_user_filter = Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('receiver').exclude(receiver=acc1.id).distinct() if acc1.role == 'manager' else Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('sender').exclude(sender=acc1.id).distinct()
        has = False
        if acc1.role == 'sharer':
            for user in all_user_filter:
                if user['sender'] == user_id :
                    has = True
            if not has:
                Message.objects.create(content="Xin chào bạn, bạn đang quan tâm đến sản phẩm nào của chúng mình ạ.", sender=acc2, receiver=acc1, time=timezone.datetime.now())

        message = Message.objects.filter(
            (models.Q(receiver=acc1) & models.Q(sender=acc2)) |
            (models.Q(receiver=acc2) & models.Q(sender=acc1))).order_by('time')

        all_user = Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('receiver').exclude(receiver=acc1.id).distinct() if acc1.role == 'manager' else Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('sender').exclude(sender=acc1.id).distinct()


        list_all_user = []
        for user in all_user:
            add_user = Manager.objects.get(pk=user['sender']) if acc1.role == 'sharer' else Sharer.objects.get(pk=user['receiver'])
            list_all_user.append(add_user)

        context = {
            'acc_id': acc_id,
            'user_id': user_id,
            'user1' : user1,
            'user2' : user2,
            'message' : message,
            'all_user': list_all_user
        }
        return render(request, "chat/chat.html", context)
#send message
def save_message(request, acc_id, user_id):
    if request.method == 'POST':
        content = request.POST.get('content', '')
        acc1 = Account.objects.get(user_ptr=request.user)
        acc2 = Account.objects.get(id = user_id)
        user1 = Sharer.objects.get(account= acc1) if acc1.role == 'sharer' else Manager.objects.get(account= acc1)
        user2 = Sharer.objects.get(account= acc2) if acc2.role == 'sharer' else Manager.objects.get(account= acc2)
        newMessage = Message.objects.create(sender=acc1, receiver=acc2, content=request.POST.get('content'), time=timezone.datetime.now()),
        message_id = newMessage[0].id
        time = newMessage[0].time
        data = {'message': content, 'time': time, 'success' : True, 'user_id': user_id, 'message_id': message_id}
        return JsonResponse(data)
#update message
def get_message(request, acc_id, user_id):
    acc1 = Account.objects.get(user_ptr=request.user)
    acc2 = Account.objects.get(id = user_id)
    user1 = Sharer.objects.get(account= acc1) if acc1.role == 'sharer' else Manager.objects.get(account= acc1)
    user2 = Sharer.objects.get(account= acc2) if acc2.role == 'sharer' else Manager.objects.get(account= acc2)
    messages = Message.objects.filter(
            (models.Q(receiver=acc1) & models.Q(sender=acc2)) |
            (models.Q(receiver=acc2) & models.Q(sender=acc1))).order_by('time')
    message_list = list(messages.values())
    user1_dic = {
        'account_id': user1.account_id,
    }
    user2_dic = {
        'account_id': user2.account_id,
    }
    data = {
        'messages': message_list,
        'success': True,
        'user1': user1_dic,
        'user2': user2_dic,
    }
    return JsonResponse(data)

profilepage/templates/chat/chat.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Chat</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'chat.css' %}">
<style type="text/css">

    </style>
</head>
<body>
<a href="{% url 'profilepage:profilePage' acc_id %}"><i style="font-size: 50px; text-decoration: none; font-weight: bold;">Back</i></a>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<div class="container">
<div class="row clearfix">
<div class="col-lg-12">
<div class="card chat-app" style="height: 500px; width: 1000px;">
<div id="plist" class="people-list">
<div class="input-group">
<div class="input-group-prepend">
<span class="input-group-text"><i class="fa fa-search"></i></span>
</div>
<input type="text" class="form-control" placeholder="Search...">
</div>
<ul class="list-unstyled chat-list mt-2 mb-0" style="max-height: 400px; overflow-y: auto;">

{% for user in all_user %}
<a href="{% url 'profilepage:chatPage' acc_id user.account_id %}">
<li class="clearfix" id="{{user.account_id}}">
<img src="{{user.avatar.url}}" alt="avatar">
<div class="about">
<div class="name">{{user.name}}</div>
<div class="status"> <i class="fa fa-circle offline"></i> left 7 mins ago </div>
</div>
</li>    
</a>
{% endfor %}

</ul>

</div>
<div class="chat" id="chat-area">
<div class="chat-header clearfix">
<div class="row">
<div class="col-lg-6">
<a href="javascript:void(0);" data-toggle="modal" data-target="#view_info">
<img src="{{user2.avatar.url}}" alt="avatar">
</a>
<div class="chat-about">
<h6 class="m-b-0">{{user2.name}}</h6>
<small>Last seen: 2 hours ago</small>
</div>
</div>
<div class="col-lg-6 hidden-sm text-right">
<a href="javascript:void(0);" class="btn btn-outline-secondary"><i class="fa fa-camera"></i></a>
<a href="javascript:void(0);" class="btn btn-outline-primary"><i class="fa fa-image"></i></a>
<a href="javascript:void(0);" class="btn btn-outline-info"><i class="fa fa-cogs"></i></a>
<a href="javascript:void(0);" class="btn btn-outline-warning"><i class="fa fa-question"></i></a>
</div>
</div>
</div>
<div class="chat-history" style="overflow-y: scroll; max-height: 350px; height: 350px;" id="chat-history">
<ul class="m-b-0" id="chat-history-ul">

    {% for mes in message %} 
    {% if mes.sender_id == user1.account_id %}
    <li class="clearfix" id="{{mes.id}}">
        <div class="message-data">
        <span class="message-data-time">{{mes.time}}</span>
        </div>
        <div class="message my-message">{{mes.content}}</div>
    </li>
    {% elif mes.sender_id == user2.account_id %}
        <li class="clearfix" id="{{mes.id}}">
        <div class="message-data text-right">
        <span class="message-data-time">{{mes.time}}</span>
        <img src="{{user2.avatar.url}}" alt="avatar">
        </div>
        <div class="message other-message float-right">{{mes.content}}</div>
        </li>
    {% endif %}
    {% endfor %}

</ul>
</div>

<div style="display: flex;" class="chat-message clearfix">
<div class="input-group mb-0">
<form id="message_form" style="height: 100%; width: 100%;" method="post" action="">
    {% csrf_token %}
<input type="text" class="form-control" placeholder="Enter text here..." id="content" name="content" required>
</div>
<div class="input-group-prepend">
    <button class="input-group-text" type="submit" id="submitButton">
        <i class="fa fa-send"></i>
    </button>
</div>
<!-- <label for="fileInput" id="imageIcon"><i class="fa fa-image"></i></label> -->
<img width="100px" height="100px" src="" alt="" id="showImg" style="display: none;">
<!-- Input thực tế để chọn file -->

</div>
</div>

<input style="opacity: 0; width: 1px; height: 1px;" type="file" id="fileInput" accept="image/*"  onchange="displaySelectedImage()">
</div>
</div>
</div>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script> 
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
	
</script>

<!-- script phan xu li hinh anh -->
<script>
        function openFileInput() {
            // Kích hoạt sự kiện click trên input thực tế
            document.getElementById('fileInput').click();
        }

        function displaySelectedImage() {
            // Hiển thị ảnh đã chọn (đường dẫn) sau khi người dùng chọn file
            const fileInput = document.getElementById('fileInput');
            const imageIcon = document.getElementById('imageIcon');

            const selectedFile = fileInput.files[0];

            if (selectedFile) {
                const reader = new FileReader();
                var url;
                reader.onload = function (e) {
                    url = e.target.result;
                    document.getElementById('showImg').src = url;

                    // Hiển thị ảnh trên biểu tượng
                };
                reader.readAsDataURL(selectedFile);
                document.getElementById('showImg').style = 'block';
            }
        }
</script>

<script>
    document.getElementById('{{user_id}}').style.backgroundColor = "#efefef";
    var csrf_token = '{{ csrf_token }}';
    var chatContainer = document.getElementById('chat-history');
    var chatHistoryUl = $('#chat-history-ul');

    function scrollToBottom() {
        chatContainer.scrollTop = chatContainer.scrollHeight;
    }
    
    // Gọi hàm scrollToBottom khi trang được tải
    window.addEventListener('load', scrollToBottom);

    $(document).ready(function() {
        $('#message_form').submit(function(e) {

            e.preventDefault();
            var content = $('#content').val().trim();
            if (content.length > 0)
                $.post('{% url "profilepage:saveMessage" acc_id user_id %}', {content: content, csrfmiddlewaretoken: csrf_token,}, function(data) {
                    if (data && data.success) {
                        chatHistoryUl.append(
                            '<li class="clearfix" id="{{message_id}}">'+
                                '<div class="message-data">'+
                                '<span class="message-data-time">'+data.time+'</span>'+
                                '</div>'+
                                '<div class="message my-message">'+data.message+'</div>'+
                            '</li>'
                        );
                        $('#content').val('');
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                        
                    } else {
                    }
                });
            else {
                
            }
        });
        function fetchMessages() {
            $.ajax({
                url: '{% url "profilepage:getMessage" acc_id user_id %}',
                type: 'GET',
                dataType: 'json',
                success: function(data) {
                    getMessage(data.messages, data.user1, data.user2);
                },
                error: function(xhr, status, error) {
                    console.error('AJAX Error:', status, error);
                }
            });
        }


        function getMessage(messages, user1, user2) {
        for (const message of messages) {
            var messageId = message.id;

            if (chatHistoryUl.find('.clearfix[id="' + messageId + '"]').length === 0) {
                if (message.sender_id == user1.account_id) {
                } else if (message.sender_id == user2.account_id) {
                    var willScrollDown = false;
                    if (Math.abs(chatContainer.scrollTop - chatContainer.scrollHeight) < 1000) {
                        willScrollDown = true;
                    } 
                    chatHistoryUl.append(
                        '<li class="clearfix" id="' + messageId + '">'+
                            '<div class="message-data text-right">'+
                            '<span class="message-data-time">'+message.time+'</span>'+
                            '<img src="{{user2.avatar.url}}" alt="avatar">'+
                            '</div>'+
                            '<div class="message my-message float-right"">'+message.content+'</div>'+
                        '</li>'
                    );
                    if (willScrollDown) {
                        chatContainer.scrollTop = chatContainer.scrollHeight;
                    }
                }
            }
        }
    }
    setInterval(fetchMessages, 500);
    });
</script>
</body>
</html>

profilepage/templates/chat/chat_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">


<title>Chat</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'chat.css' %}">
</head>
<body>
<a href="{% url 'profilepage:profilePage' acc_id %}"><i style="font-size: 50px; text-decoration: none; font-weight: bold;">Back</i></a>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
<div class="container">
<div class="row clearfix">
<div class="col-lg-12">
<div class="card chat-app" style="height: 500px; width: 1000px;">
<div id="plist" class="people-list">
<div class="input-group">
<div class="input-group-prepend">
<span class="input-group-text"><i class="fa fa-search"></i></span>
</div>
<input type="text" class="form-control" placeholder="Search...">
</div>
<ul class="list-unstyled chat-list mt-2 mb-0" style="max-height: 400px; overflow-y: auto;">

{% for user in all_user %}
<a href="{% url 'profilepage:chatPage' acc_id user.account_id %}">
<li class="clearfix" id="{{user.account_id}}">
<img src="{{user.avatar.url}}" alt="avatar">
<div class="about">
<div class="name">{{user.name}}</div>
<div class="status"> <i class="fa fa-circle offline"></i> left 7 mins ago </div>
</div>
</li>    
</a>
{% endfor %}

</ul>

</div>
<div class="chat" style="height: 100%;" id="chat-area">
    <img src="https://www.socialintents.com/blog/wp-content/uploads/2021/07/Live-chat-welcome-message.jpg" style="height: auto; width: 100%;">
</div>

</div>
</div>
</div>
</div>
<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/js/bootstrap.bundle.min.js"></script>
<script type="text/javascript">
	
</script>

   
</body>
</html>