bkvivu/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from profilepage import views as profileViews
from django.shortcuts import redirect

urlpatterns = [
    path('', lambda request: redirect('homepage/')),
    path('admin/', admin.site.urls),
    path('logout/', profileViews.logout_view, name = 'logout'),
    path('homepage/', include('homepage.urls')),
    path('postspage/', include('postspage.urls')),
    path('profile/', include('profilepage.urls')),
    path('settings/', include('settingspage.urls')),
    path('shoppingcart/', include('shoppingcart.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path, include
from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.homePage, name='homePage'),
    path('login/', views.loginPage, name='loginPage'),
    path('login/register/', views.registerPage, name='registerPage'),
    path('update_likes/<int:post_id>/', views.update_likes, name='update_likes'),

    path('searchTag/<str:tag>/', views.searchTag, name='searchTag'),
    path('search/', views.mainSearch, name='mainSearch'),
]

postspage/urls.py
from django.urls import path, include
from . import views

# 3/12
from django.conf import settings
from django.conf.urls.static import static

app_name = 'postspage'
urlpatterns = [
    path('', views.postsPage, name='postsPage'),
    path('posts/', views.postsView, name='posts'),
    
    path('restaurants/', views.restaurantsView, name='restaurants'),
    path('update_likes/<int:post_id>/', views.update_likes, name='update_likes'),
    path('insert_comment/<int:post_id>/', views.insert_comment, name='insert_comment'),
    path('delete_comment/<int:comment_id>/', views.delete_comment, name='insert_comment'),
    path('get_comments/<int:post_id>/', views.get_comments, name='get_comments'),
    path('search/', views.searchPosts, name='search_post'),
    path('search/detail/<int:post_id>/', views.detailPost, name='detail_post'),
    # path('test', views.test, name='test')
]   + static(settings.MEDIA_URL, document_root = settings.MEDIA_URL) # 3/12

profilepage/urls.py
from django.urls import path, include
from . import views

app_name = 'profilepage'
urlpatterns = [
    path('<int:acc_id>/', views.profilePage, name='profilePage'),
    path('logout/', views.logout_view, name='logoutPage'),
    path('<int:acc_id>/vote', views.voteProfile, name='voteProfile'),
    path('<int:acc_id>/chatDefault', views.chatPageDefault, name='chatDefault'),
    path('<int:acc_id>/chat/<int:user_id>/', views.chatPage, name='chatPage'),
    path('<int:acc_id>/chat/<int:user_id>/save', views.save_message, name='saveMessage'),
    path('<int:acc_id>/chat/<int:user_id>/get', views.get_message, name='getMessage'),
]

settingspage/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'settingspage'
urlpatterns = [
    path('', views.settingsPage, name='settingsPage'),
    path('general/', views.generalPage, name='gerenalPage'),

    path('posts', views.testPostPage, name='testPostPage'),
    path('posts/addPosts', views.testCreatePosts, name='testCreatePosts'),
    path('posts/delete/<int:postId>/', views.testDeletePost, name='testDeletePost'),
    path('posts/edit/<int:postId>/', views.testEditPost, name="testEditPost"),
    path('posts/edit/<int:postId>/testDeleteImagePost/<int:imageId>', views.testDeleteImagePost, name='testDeleteImagePost'),
    path('posts/edit/<int:postId>/testRecoverDelete/', views.testRecoverDelete, name="testRecoverDelete"),

    path('product/', views.ProductManager, name='product'),
    path('product/add', views.CreateProduct.as_view(), name='addProduct'),
    path('product/delete/<int:product_id>', views.deleteProduct, name='deleteProduct'),
    path('product/edit/<int:product_id>', views.editProduct.as_view(), name='editProduct'),


    path('bills/', views.billsPage, name='billsPage'),
    path('bills/viewBill/<int:billId>', views.viewBill, name='viewBill'),
    path('bills/viewBill/<int:billId>/accept/>', views.accept, name='accept'),
    path('bills/viewBill/<int:billId>/decline/>', views.decline, name='decline'),


    path('statistics/', views.statisticsPage, name='statisticsPage'),

    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_URL)

shoppingcart/urls.py
from django.urls import path, include
from . import views

app_name = 'shoppingcart'
urlpatterns = [
    path('', views.viewShoppingCart, name ='shoppingCart'),
    path('update_quantity/', views.updateQuantity, name='updateQuantity'),
    path('create_bill/', views.createBill, name='createBill'),
    path('payment/<int:bill_id>/', views.Payment.as_view(), name='paymentPage'),
    path('cancelpayment/<int:bill_id>/', views.cancelPayment, name = 'cancelPayment'),
    path('timeoutpayment/<int:bill_id>/', views.timeoutPayment, name = 'timeoutPayment'),
    path('orderlist/', views.OrderList.as_view(), name= 'orderList'),
    path('addToCart/', views.addToCart, name='addItem'),

]

profilepage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib import messages

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.contrib.auth import logout
from .models import *
from homepage.models import *


# Create your views here.
def profilePage(request, acc_id):
    if not request.user.is_authenticated:
        return redirect('homepage:loginPage')
    # target_acc , target_user : đối tượng mà mình vào xem trang cá nhân
    target_acc = Account.objects.get(pk=acc_id)
    target_user = Sharer.objects.get(account= target_acc) if target_acc.role == 'sharer' else Manager.objects.get(account= target_acc)
    # acc, user : Bản thân người đang đăng nhập
    acc = Account.objects.get(user_ptr=request.user)
    user = Sharer.objects.get(account= acc) if acc.role == 'sharer' else Manager.objects.get(account= acc)
    # Lấy số sao đã vote của người đăng nhập nếu profile đang xem là Manager
    starsvotetarget = 5
    if(target_acc.role == 'manager') and (target_acc.id != acc.id):
        try:
            voteobj = StarVote.objects.get(account=acc, manager= target_user)
            starsvotetarget = voteobj.stars
        except:
            pass
    # Danh sách những bài viết mà người dùng đã like
    listPosts = Post.objects.filter(account = target_acc).order_by('-time')
 
    listPostsLike = []
    for _posts in listPosts:
        if UserLike.objects.filter(account= acc, post = _posts):
            listPostsLike.append(_posts)
    context = {
        'acc': acc,
        'target_user': target_user,
        'user': user,
        'starsvotetarget': starsvotetarget,
        'listPosts': listPosts,
        'listPostsLike' : listPostsLike
    }
    return render(request, 'profile.html', context)

#vote Profile manager
def voteProfile(request,acc_id):
    if request.method == 'POST':
        try:
            acc = Account.objects.get(user_ptr=request.user)
            target_user=Manager.objects.get(account= acc_id)
            stars = request.POST.get("rate")
            # Lấy hoặc tạo một đối tượng StarVote dựa trên account_id và manager_id
            star_vote, created = StarVote.objects.get_or_create(
                account = acc,
                manager = target_user,
                defaults={'stars': stars}  # Điền vào giá trị mặc định cho số sao nếu đối tượng chưa tồn tại
            )
            if not created:
            # Đối tượng đã tồn tại, bạn có thể thực hiện các thay đổi tùy thuộc vào trường hợp của bạn
                star_vote.stars = stars
                star_vote.save()
            target_user.save() #Cập nhật rank cho người quản lý
        except:
            pass
    else:
        pass
    return redirect('profilepage:profilePage', acc_id=acc_id)

# Log out button
def logout_view(request):
    if not request.user.is_authenticated:
        return redirect('homepage:loginPage')
    logout(request)
    return redirect('homepage:homePage')



#Chat
def chatPageDefault(request, acc_id):
    if request.method == 'GET':
        acc1 = Account.objects.get(user_ptr=request.user)
        user1 = Sharer.objects.get(account= acc1) if acc1.role == 'sharer' else Manager.objects.get(account= acc1)

        all_user = Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('receiver').exclude(receiver=acc1.id).distinct() if acc1.role == 'manager' else Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('sender').exclude(sender=acc1.id).distinct()

        #default : tuong tac 2 chieu roi, i send you , you send me
        list_all_user = []
        for user in all_user:
            add_user = Manager.objects.get(pk=user['sender']) if acc1.role == 'sharer' else Sharer.objects.get(pk=user['receiver'])
            list_all_user.append(add_user)

        context = {
            'acc_id': acc_id,
            'user1' : user1,
            'all_user': list_all_user
        }
        return render(request, "chat/chat_base.html", context)
    
def chatPage(request, acc_id, user_id):
    if request.method == 'GET':
        acc1 = Account.objects.get(user_ptr=request.user)
        acc2 = Account.objects.get(id = user_id)
        user1 = Sharer.objects.get(account= acc1) if acc1.role == 'sharer' else Manager.objects.get(account= acc1)
        user2 = Sharer.objects.get(account= acc2) if acc2.role == 'sharer' else Manager.objects.get(account= acc2)
        # check if user2 has conversation with user1, if not initialize it
        all_user_filter = Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('receiver').exclude(receiver=acc1.id).distinct() if acc1.role == 'manager' else Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('sender').exclude(sender=acc1.id).distinct()
        has = False
        if acc1.role == 'sharer':
            for user in all_user_filter:
                if user['sender'] == user_id :
                    has = True
            if not has:
                Message.objects.create(content="Xin chào bạn, bạn đang quan tâm đến sản phẩm nào của chúng mình ạ.", sender=acc2, receiver=acc1, time=timezone.datetime.now())

        message = Message.objects.filter(
            (models.Q(receiver=acc1) & models.Q(sender=acc2)) |
            (models.Q(receiver=acc2) & models.Q(sender=acc1))).order_by('time')

        all_user = Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('receiver').exclude(receiver=acc1.id).distinct() if acc1.role == 'manager' else Message.objects.filter(
        models.Q(sender=acc1) | models.Q(receiver=acc1)).values('sender').exclude(sender=acc1.id).distinct()


        list_all_user = []
        for user in all_user:
            add_user = Manager.objects.get(pk=user['sender']) if acc1.role == 'sharer' else Sharer.objects.get(pk=user['receiver'])
            list_all_user.append(add_user)

        context = {
            'acc_id': acc_id,
            'user_id': user_id,
            'user1' : user1,
            'user2' : user2,
            'message' : message,
            'all_user': list_all_user
        }
        return render(request, "chat/chat.html", context)
#send message
def save_message(request, acc_id, user_id):
    if request.method == 'POST':
        content = request.POST.get('content', '')
        acc1 = Account.objects.get(user_ptr=request.user)
        acc2 = Account.objects.get(id = user_id)
        user1 = Sharer.objects.get(account= acc1) if acc1.role == 'sharer' else Manager.objects.get(account= acc1)
        user2 = Sharer.objects.get(account= acc2) if acc2.role == 'sharer' else Manager.objects.get(account= acc2)
        newMessage = Message.objects.create(sender=acc1, receiver=acc2, content=request.POST.get('content'), time=timezone.datetime.now()),
        message_id = newMessage[0].id
        time = newMessage[0].time
        data = {'message': content, 'time': time, 'success' : True, 'user_id': user_id, 'message_id': message_id}
        return JsonResponse(data)
#update message
def get_message(request, acc_id, user_id):
    acc1 = Account.objects.get(user_ptr=request.user)
    acc2 = Account.objects.get(id = user_id)
    user1 = Sharer.objects.get(account= acc1) if acc1.role == 'sharer' else Manager.objects.get(account= acc1)
    user2 = Sharer.objects.get(account= acc2) if acc2.role == 'sharer' else Manager.objects.get(account= acc2)
    messages = Message.objects.filter(
            (models.Q(receiver=acc1) & models.Q(sender=acc2)) |
            (models.Q(receiver=acc2) & models.Q(sender=acc1))).order_by('time')
    message_list = list(messages.values())
    user1_dic = {
        'account_id': user1.account_id,
    }
    user2_dic = {
        'account_id': user2.account_id,
    }
    data = {
        'messages': message_list,
        'success': True,
        'user1': user1_dic,
        'user2': user2_dic,
    }
    return JsonResponse(data)

profilepage/templates/profilepage/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'header.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'votestyle.css' %}">
    <link rel="stylesheet" href="{% static 'postStyle.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://kit.fontawesome.com/bc4d8a1311.js" crossorigin="anonymous"></script>
    <script src="{% static 'votescript.js' %}"></script>
    <script src="{% static 'postScript.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/>
</head>
<body>
    <div class="header" style="padding: 0px 35px;">
        <div class="left">
            <a href="{% url 'homepage:homePage' %}" class="logo">
                <img src="{% static 'images/logo.png' %}"  alt="logo">
                <div class = "description">
                    <h2><strong>BKvivu</strong></h2>
                    <p style="width: 400px;">Nền tảng chia sẻ dịch vụ hàng đầu</p>
                </div> 
            </a>
        </div>
            
        <div class="right">
            <div id="-box-nav">
                <a href="{% url 'postspage:posts' %}" id="community"><i class="fa fa-fw fa-users"></i>Khám phá</a>
                <div class="subnav">
                    <a href="{% url 'postspage:restaurants' %}">Cửa hàng</a>
                    <a href="{% url 'postspage:posts' %}">Bài chia sẻ</a>
                </div>
            </div>
            {% if acc.role == 'sharer' %}
            <div class="setting_icon">
                <a href="{% url 'shoppingcart:shoppingCart'  %}" class="setting">
                    <div >
                        <i class="fa-solid fa-cart-shopping"></i>
                    <span>Cart</span>
                    </div>
                </a>
            </div>
            {% endif %}
            <div class="setting_icon">
                <a href="{% url 'settingspage:settingsPage' %}" class="setting">
                    <div >
                    <i class="fa-solid fa-gear"></i>
                    <span>Settings</span>
                    </div>
                </a>
            </div>
            <div class="setting_icon">
                <a href="/logout/" class="setting">
                    <div>
                        <i class="fa-solid fa-arrow-right-from-bracket"></i>
                    <span>Logout</span>
                    </div>
                </a>
            </div>
            <a href="{% url 'profilepage:profilePage' acc.id%}" class="logo-user" style="width: auto;">
                <img class="img-user" src = "{{user.avatar.url}}"/>
            </a>
            
        </div>
    </div>
    <!-- Chat logo -->
    <div class="chatbox">
        <a href="{% url 'profilepage:chatDefault' target_user.account_id %}" class="chat-link">
            <div class="chat-label">
                <i class="fa-solid fa-message"></i>
                <span>Chat</span>
            </div>
        </a>
    </div>


    <!--Top navbar -->
    <!--<div class="topnav">
        <a href="{% url 'homepage:homePage' %}" class="logo-home">
            <div class="logo">

            </div>
            <div class="app-name">
                <h4>BKvivu</h4>
                <span class="">Nền tảng chia sẻ dịch vụ hàng đầu</span>
            </div>
        </a>
        <div class="option">
            <a href="{% url 'profilepage:profilePage' user.account.id%}" class="my-profile">
                <div>
                <i class="fa-solid fa-user"></i>
                <span>My Profile</span>
                </div>
            </a>

            <a href="{% url 'settingspage:settingsPage' %}" class="setting">
                <div >
                <i class="fa-solid fa-gear"></i>
                <span>Settings</span>
                </div>
            </a>

            {% if user.account.role == "sharer" %}
            <a href="{% url 'shoppingcart:shoppingCart'%}" class="log-out">
                <div>
                <i class="fa-solid fa-cart-shopping"></i>
                <span>Giỏ hàng</span>
                </div>
            </a>
            {% endif %}
            <a href="{% url 'profilepage:logoutPage'%}" class="log-out">
                <div>
                <i class="fa-solid fa-right-from-bracket"></i>
                <span>Log out</span>
                </div>
            </a>

        </div>
    </div>
-->
    <!-- Info profile -->
    <div class="top-profile" {% if target_user.account.role == 'sharer' %}style="background-color: white;"{% endif %}>
        <div class="avatar-name">
            <div class="avatar">
                <img src = "{{ target_user.avatar.url}}" alt="">
                {% if target_user.account.role == 'manager' %}<i class="fa-solid fa-shop"></i>{% endif %}
            </div>
            <div class="name">
                <h1 id="name-profile">{{ target_user.name }}</h2>
                {% if target_user.account.role == 'manager' %}
                    {% block rateProfile %}
                    {% endblock rateProfile %}
                {% endif %}
            </div>
            {% if target_user.account.role == 'manager' and user.account.role == 'sharer' %}
            <div>
                <a href="{% url 'profilepage:chatPage' target_user.account.id target_user.account.id %}">
                    <i style="font-size: 40px;" class="fas fa-comment-dots"></i>
                </a>
            </div>
            {% endif %}
        </div>
    {% if target_user.account.role == "manager" %}
        {% block infoProfileManager %}
        {% endblock infoProfileManager %}
    {% endif %}
    </div>
    <!--  buttom-profile of manager account-->
    {% if target_user.account.role == "manager" %}
        {% block buttom_profile %}
        {% endblock buttom_profile %}
    {% endif %}
    <!-- Contents -->
    <div class="contents">
        <div class="top-contents">
            <div class="top-contents-left">
                <i class="fa-solid fa-newspaper"></i>
                <h1>Bài viết</h1>
            </div>
            <div class="top-contents-right">

            </div>
        </div>
        <div class="list-contents">

            {% if target_user.account and listPosts%}
            <ul>
                {% for posts in listPosts %}
                    <!-- Post # -->
                    <li class="item">
                        <div class="info-post">
                            <a href="{% url 'profilepage:profilePage' target_user.account.id%}">
                                <img src="{{target_user.avatar.url}}" alt="{{target_user.name}}" class="avatar-post">
                            </a>
                            <h3><strong>{{target_user.name}}</strong></h3>
                            <h6>Time: <strong>{{posts.time}}</strong></h6>
                            <p>
                            {% if posts.provider %}
                                Đang ở: <a href="{% url 'profilepage:profilePage' posts.provider.account.id%}"><strong>{{posts.provider.name}}</strong></a>
                            {% else %}
                                {% if posts.ward and posts.district and posts.city%}
                                    <i class="fa-solid fa-location-dot"></i>
                                        {{posts.ward}} - {{posts.district}} - {{posts.city}} ({{posts.address}})
                                {% endif %}
                            {% endif %}
                            </p>
                        </div>
                        <h3 style="margin: 5px 0;"><strong>{{posts.title}}</strong></h3>
                        <p style="white-space: pre-line;">{{posts.content}}</p>

                        {% if posts.image_set.all %}
                        <div class="post-photo">
                            {% for image in posts.image_set.all %}
                            <img src="{{image.img.url}}" alt="{{posts.title}} 1" class="photo">
                            {% endfor %}
                        </div>
                        {% endif %}

                        <div class="post-actions">
                            <!-- LIKE -->
                            {% if posts in listPostsLike %}
                            <button value="true" onclick="likeAction(event, {{posts.id}})" style="background-color: #f00;">
                            {% else %}
                            <button value="false" onclick="likeAction(event, {{posts.id}})">
                            {% endif %}
                                <big id="{{posts.id}}_like">{{posts.like}} </big>
                                <i class="far fa-thumbs-up"></i>
                            </button>
                            <!-- Comment -->
                            <button onclick="showComment(event, {{ posts.id }})">
                                <big id="{{posts.id}}_commentNum">{{posts.commentNum}} </big>
                                <i class="far fa-comment"></i>
                            </button>
                        </div>

                        <div class="post-comment">
                            <img src="{{user.avatar.url}}" alt="" class="avatar">
                            <input type="text" placeholder="Viết bình luận ..." class="comment-input" id="{{posts.id}}_comment">
                            <button class="sendCmt" onclick="insertComment(event, {{posts.id}})"> Gửi</button>
                        </div>
                        {% comment %} ----------Comments----------- {% endcomment %}
                    </li>
                    {% comment %} End post {% endcomment %}
                {% endfor %}
            </ul>
            <div class="list-comment-container" id="containerComment">
                <div class="list-comment">
                    <div class="close-comment">
                        <button id="cancelButton" onclick="cancelComment()"><i class="fa-solid fa-rectangle-xmark"></i></button>
                    </div>
                  <section class="gradient-custom">
                    <div class="container-comment" style="display: block;">
                        <h4>Comments</h4>
                        <div class="col" id="allCommentOfPostId">
                            {% comment %} List Comments {% endcomment %}
                        </div>
                    </div>
                  </section>
                </div>
              </div>
            {% else %}
                <h3 style="padding: 20px 20px 20px 20px;">Người này hiện chưa có bài viết nào!</h3>
            {% endif %}
            <!-- End listpost -->
        </div>
    </div>

    <!-- Footer -->
    <footer class="footer">
        <div class="waves">
          <div class="wave" id="wave1"></div>
          <div class="wave" id="wave2"></div>
          <div class="wave" id="wave3"></div>
          <div class="wave" id="wave4"></div>
        </div>
        <ul class="social-icon">
          <li class="social-icon__item"><a class="social-icon__link" href="#">
              <ion-icon name="logo-facebook"></ion-icon>
            </a></li>
          <li class="social-icon__item"><a class="social-icon__link" href="#">
              <ion-icon name="logo-twitter"></ion-icon>
            </a></li>
          <li class="social-icon__item"><a class="social-icon__link" href="#">
              <ion-icon name="logo-linkedin"></ion-icon>
            </a></li>
          <li class="social-icon__item"><a class="social-icon__link" href="#">
              <ion-icon name="logo-instagram"></ion-icon>
            </a></li>
        </ul>
        <ul class="menu">
          <li class="menu__item"><a class="menu__link" href="#">Home</a></li>
          <li class="menu__item"><a class="menu__link" href="#">About</a></li>
          <li class="menu__item"><a class="menu__link" href="#">Services</a></li>
          <li class="menu__item"><a class="menu__link" href="#">Team</a></li>
          <li class="menu__item"><a class="menu__link" href="#">Contact</a></li>

        </ul>
        <p>&copy;2023 BKvivu | BaoDungDatDatThanhTruong</p>
    </footer>


    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
</body>
</html>